# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'wMain.ui'
##
## Created by: Qt User Interface Compiler version 5.15.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.ApplicationModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(343, 143)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(343, 143))
        MainWindow.setMaximumSize(QSize(343, 143))
        MainWindow.setBaseSize(QSize(343, 142))
        font = QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setCursor(QCursor(Qt.ClosedHandCursor))
        MainWindow.setFocusPolicy(Qt.NoFocus)
        MainWindow.setToolTipDuration(-1)
        MainWindow.setLayoutDirection(Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setSizeConstraint(QLayout.SetMinimumSize)
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        sizePolicy1 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy1)
        self.groupBox.setMinimumSize(QSize(323, 59))
        self.groupBox.setMaximumSize(QSize(323, 59))
        self.verticalLayout_6 = QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.lineEditEnterIP = QLineEdit(self.groupBox)
        self.lineEditEnterIP.setObjectName(u"lineEditEnterIP")
        sizePolicy2 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Maximum)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.lineEditEnterIP.sizePolicy().hasHeightForWidth())
        self.lineEditEnterIP.setSizePolicy(sizePolicy2)
        self.lineEditEnterIP.setMinimumSize(QSize(279, 29))
        self.lineEditEnterIP.setMaximumSize(QSize(279, 29))
        font1 = QFont()
        font1.setFamily(u"Terminal")
        font1.setPointSize(14)
        font1.setBold(True)
        font1.setItalic(False)
        font1.setUnderline(False)
        font1.setWeight(75)
        font1.setStrikeOut(False)
        self.lineEditEnterIP.setFont(font1)
        self.lineEditEnterIP.setMaxLength(15)
        self.lineEditEnterIP.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_2.addWidget(self.lineEditEnterIP)


        self.verticalLayout_6.addLayout(self.horizontalLayout_2)


        self.verticalLayout_2.addWidget(self.groupBox, 0, Qt.AlignHCenter|Qt.AlignVCenter)


        self.verticalLayout.addLayout(self.verticalLayout_2)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(-1, 0, 0, 0)
        self.pushButton_5556 = QPushButton(self.centralwidget)
        self.pushButton_5556.setObjectName(u"pushButton_5556")
        self.pushButton_5556.setEnabled(True)
        sizePolicy3 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.pushButton_5556.sizePolicy().hasHeightForWidth())
        self.pushButton_5556.setSizePolicy(sizePolicy3)
        font2 = QFont()
        font2.setFamily(u"Arial Black")
        font2.setPointSize(14)
        font2.setBold(False)
        font2.setItalic(False)
        font2.setWeight(50)
        self.pushButton_5556.setFont(font2)
        self.pushButton_5556.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_5556.setToolTipDuration(2000)
        self.pushButton_5556.setCheckable(True)

        self.horizontalLayout.addWidget(self.pushButton_5556, 0, Qt.AlignHCenter|Qt.AlignVCenter)

        self.pushButton_30001 = QPushButton(self.centralwidget)
        self.pushButton_30001.setObjectName(u"pushButton_30001")
        sizePolicy3.setHeightForWidth(self.pushButton_30001.sizePolicy().hasHeightForWidth())
        self.pushButton_30001.setSizePolicy(sizePolicy3)
        self.pushButton_30001.setFont(font2)
        self.pushButton_30001.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_30001.setToolTipDuration(2000)
        self.pushButton_30001.setCheckable(True)
        self.pushButton_30001.setAutoDefault(False)
        self.pushButton_30001.setFlat(False)

        self.horizontalLayout.addWidget(self.pushButton_30001, 0, Qt.AlignHCenter|Qt.AlignVCenter)

        self.pushButton_30002 = QPushButton(self.centralwidget)
        self.pushButton_30002.setObjectName(u"pushButton_30002")
        sizePolicy3.setHeightForWidth(self.pushButton_30002.sizePolicy().hasHeightForWidth())
        self.pushButton_30002.setSizePolicy(sizePolicy3)
        self.pushButton_30002.setFont(font2)
        self.pushButton_30002.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_30002.setToolTipDuration(2000)
        self.pushButton_30002.setCheckable(True)

        self.horizontalLayout.addWidget(self.pushButton_30002, 0, Qt.AlignHCenter|Qt.AlignVCenter)

        self.pushButton_30003 = QPushButton(self.centralwidget)
        self.pushButton_30003.setObjectName(u"pushButton_30003")
        sizePolicy3.setHeightForWidth(self.pushButton_30003.sizePolicy().hasHeightForWidth())
        self.pushButton_30003.setSizePolicy(sizePolicy3)
        font3 = QFont()
        font3.setFamily(u"Arial Black")
        font3.setPointSize(14)
        font3.setBold(False)
        font3.setItalic(False)
        font3.setUnderline(False)
        font3.setWeight(50)
        self.pushButton_30003.setFont(font3)
        self.pushButton_30003.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_30003.setToolTipDuration(2000)
        self.pushButton_30003.setCheckable(True)

        self.horizontalLayout.addWidget(self.pushButton_30003, 0, Qt.AlignHCenter|Qt.AlignVCenter)


        self.verticalLayout.addLayout(self.horizontalLayout)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        font4 = QFont()
        font4.setFamily(u"Courier New")
        font4.setBold(True)
        font4.setItalic(True)
        font4.setWeight(75)
        self.statusbar.setFont(font4)
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_30002.toggled.connect(MainWindow.pushButton_30002click)
        self.pushButton_30003.toggled.connect(MainWindow.pushButton_30003click)
        self.pushButton_5556.toggled.connect(MainWindow.pushButton_5556click)
        self.pushButton_30001.toggled.connect(MainWindow.pushButton_30001click)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"iClebo O5", None))
#if QT_CONFIG(tooltip)
        MainWindow.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        MainWindow.setStatusTip("")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        MainWindow.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Robot IP: ", None))
#if QT_CONFIG(tooltip)
        self.lineEditEnterIP.setToolTip(QCoreApplication.translate("MainWindow", u"enter IP4 of Robot Omega_O5", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEditEnterIP.setStatusTip(QCoreApplication.translate("MainWindow", u"enter IP4 of Robot", None))
#endif // QT_CONFIG(statustip)
        self.lineEditEnterIP.setText(QCoreApplication.translate("MainWindow", u"WAIT...Scan IP!", None))
#if QT_CONFIG(tooltip)
        self.pushButton_5556.setToolTip(QCoreApplication.translate("MainWindow", u"show info from port 5556", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_5556.setStatusTip(QCoreApplication.translate("MainWindow", u"start ip:5556", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_5556.setText(QCoreApplication.translate("MainWindow", u"5556", None))
#if QT_CONFIG(tooltip)
        self.pushButton_30001.setToolTip(QCoreApplication.translate("MainWindow", u"show info from port 30001", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_30001.setStatusTip(QCoreApplication.translate("MainWindow", u"start ip:30001", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_30001.setText(QCoreApplication.translate("MainWindow", u"30001", None))
#if QT_CONFIG(tooltip)
        self.pushButton_30002.setToolTip(QCoreApplication.translate("MainWindow", u"show info from port 30002", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_30002.setStatusTip(QCoreApplication.translate("MainWindow", u"start ip:30002", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_30002.setText(QCoreApplication.translate("MainWindow", u"30002", None))
#if QT_CONFIG(tooltip)
        self.pushButton_30003.setToolTip(QCoreApplication.translate("MainWindow", u"show info from port 30003", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_30003.setStatusTip(QCoreApplication.translate("MainWindow", u"start ip:30003", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_30003.setText(QCoreApplication.translate("MainWindow", u"30003", None))
    # retranslateUi

